### PR TITLE
Disabled scroll when hamburger menu is opened

### PR DESCRIPTION
**Pull request by VarshaSulakhe**

### CODE REVIEW

**Comment by cjchirag7** [comment]
Please update your repo to the latest version, so that I can test it and  merge if it is apt.

**Comment by cjchirag7** [comment]
Good try, but one bug:
The scroll goes to the page-top when hamburger menu is opened, and when the menu is closed again, it doesn't return the scroll to its original position.

**Comment by cjchirag7** [comment]
try to change the overflow property of body to block scroll, when user clicks the hamburger

**Comment by VarshaSulakhe** [comment]
Updated the PR with the changes

**Pull request closed without merging**
